[package]
name = "rust-learning"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]


[dev-dependencies]
anyhow = "1.0.83"
futures = "0.3.30"
oneshot = "0.1.6"
rand = "0.8.5"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
